module.exports = prisma => Promise.all([
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'Role', value: 'ADMIN', label: 'Administrador' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'Role', value: 'MANAGER', label: 'Manager' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'Role', value: 'SUPERVISOR', label: 'Supervisor' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'Role', value: 'HR', label: 'Recursos Humanos' } }, `{ id }`),

  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'Boolean', value: 'true', label: 'Si' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'Boolean', value: 'false', label: 'No' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'EmployeeSex', value: 'F', label: 'Feminino' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'EmployeeSex', value: 'M', label: 'Masculino' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'EmployeeDocumentType', value: 'CI', label: 'Carnet de Identidad' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'EmployeeDocumentType', value: 'PASSAPORTE', label: 'Passaporte' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'EmployeeCajaDeSalud', value: 'OPTION_1', label: 'Caja Nacional de Salud (C.N.S.)' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'EmployeeCajaDeSalud', value: 'OPTION_2', label: 'Caja Petrolera de Salud (C.P.S.)' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'EmployeeCajaDeSalud', value: 'OPTION_3', label: 'Caja de Salud de Caminos' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'EmployeeCajaDeSalud', value: 'OPTION_4', label: 'Caja Bancaria Estatal de Salud (C.B.E.S.)' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'EmployeeCajaDeSalud', value: 'OPTION_5', label: 'Caja de Salud de la Banca Privada (C.S.B.P.)' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'EmployeeCajaDeSalud', value: 'OPTION_6', label: 'Caja de Salud Cordes' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'EmployeeCajaDeSalud', value: 'OPTION_7', label: 'Seguro Social Universitario (S.I.S.S.U.B.)' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'EmployeeCajaDeSalud', value: 'OPTION_8', label: 'Corporación del Seguro Social Militar (COOSMIL)' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'EmployeeCajaDeSalud', value: 'OPTION_9', label: 'Seguro Integral de Salud (SINEC)' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'EmployeeAFP', value: 'OPTION_1', label: 'AFP Previsión' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'EmployeeAFP', value: 'OPTION_2', label: 'AFP Futuro' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'ContractWorkClass', value: 'OPTION_1', label: 'Ocupaciones de dirección en la administración pública y empresas' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'ContractWorkClass', value: 'OPTION_2', label: 'Ocupaciones de profesionales científicos e intelectuales' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'ContractWorkClass', value: 'OPTION_3', label: 'Ocupaciones de técnicos y profesionales de apoyo' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'ContractWorkClass', value: 'OPTION_4', label: 'Empleados de oficina' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'ContractWorkClass', value: 'OPTION_5', label: 'Trabajadores de los servicios y vendedores del comercio' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'ContractWorkClass', value: 'OPTION_6', label: 'Productores y trabajadores en la agricultura, pecuaria, agropecuaria y pesca' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'ContractWorkClass', value: 'OPTION_7', label: 'Trabajadores de la industria extractiva, construcción, industria manufacturera y otros oficios' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'ContractWorkClass', value: 'OPTION_8', label: 'Operadores de instalaciones y maquinarias' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'ContractWorkClass', value: 'OPTION_9', label: 'Trabajadores no calificados' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'ContractWorkClass', value: 'OPTION_10', label:  'Fuerzas armada' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'ContractModality', value: 'OPTION_1', label: 'Tiempo indefinido' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'ContractModality', value: 'OPTION_2', label: 'A plazo fijo' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'ContractModality', value: 'OPTION_3', label: 'Por temporada' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'ContractModality', value: 'OPTION_4', label: 'Por realización de obra o servicio' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'ContractModality', value: 'OPTION_5', label: 'Condicional o eventual' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'ContractType', value: 'OPTION_1', label: 'Escrito' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'ContractType', value: 'OPTION_2', label: 'Verbal' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'ContractCancelMotive', value: 'OPTION_1', label: 'Retiro voluntario del trabajador' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'ContractCancelMotive', value: 'OPTION_2', label: 'Vencimiento de contrato' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'ContractCancelMotive', value: 'OPTION_3', label: 'Conclusión de obra' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'ContractCancelMotive', value: 'OPTION_4', label: 'Perjuicio material causado con intención en los instrumentos de trabajo' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'ContractCancelMotive', value: 'OPTION_5', label: 'Revelación de secretos industriales' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'ContractCancelMotive', value: 'OPTION_7', label: 'Inasistencia injustificada de más de seis días continuos' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'ContractCancelMotive', value: 'OPTION_6', label: 'Omisiones o imprudencias que afecten a la seguridad o higiene industrial' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'ContractCancelMotive', value: 'OPTION_8', label: 'Incumplimiento total o parcial del convenio' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'ContractCancelMotive', value: 'OPTION_9', label: 'Robo o hurto por el trabajador' } }, `{ id }`),
  prisma.bindings.mutation.createFieldOptionLabel({ data: { field: 'ContractCancelMotive', value: 'OPTION_10', label: 'Retiro forzoso' } }, `{ id }`),
])