version: '3'
services:
  prisma:
    environment:
      PRISMA_CONFIG: |
        port: 4466
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        databases:
          default:
            connector: postgres
            host: ${PG_HOST:-postgres-db}
            port: ${PG_PORT:-5432}
            database: ${PG_DATABASE}
            user: ${PG_USERNAME}
            password: ${PG_PASSWORD}
            migrations: true # allow prisma to change the database structure
            # connectionLimit: 50
  postgres-db:
    image: postgres:10-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
  wasp:
    image: wasp:latest-dev
    build:
      args:
        NODE_ENV: development
    command: nodemon -L src/index.js
    environment:
      NODE_ENV: development
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
      # - ./src:/usr/app/src
      # - ./data:/usr/app/data
volumes:
  postgres: