# production configuration. See docker-compose.override.yml from development specific configurations
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.21
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        databases:
          default:
            connector: postgres
            host: ${PG_HOST:-host.docker.internal}
            port: ${PG_PORT:-5432}
            database: ${PG_DATABASE}
            user: ${PG_USERNAME}
            password: ${PG_PASSWORD}
            migrations: true # allow prisma to change the database structure
            # connectionLimit: 50
  wasp:
    build:
      context: .
      args:
        NODE_ENV: production
    ports:
      - "4000:4000"
    restart: always
    environment:
      NODE_ENV: production
      PRISMA_ENDPOINT: ${PRISMA_ENDPOINT}
      PRISMA_SECRET: ${PRISMA_SECRET}
      APP_SECRET: ${APP_SECRET}
      BCRYPT_SALT_ROUNDS: ${BCRYPT_SALT_ROUNDS-12}
      ZKTIME_DB_PATH: ${ZKTIME_DB_PATH}
    depends_on:
      - prisma
