version: '3'
services:
  postgres-db:
    image: postgres:10-alpine
    restart: always
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
  wasp:
    build: .
    command: nodemon -L src/index.js
    volumes:
      - ./src:/usr/app/src
      - ./data:/usr/app/data
volumes:
  postgres: