version: '3'
services:
  postgres-db:
    image: postgres:10-alpine
    restart: always
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
  wasp:
    command: nodemon -L src/index.js
    # ports:
    #   - "4000:4000"
    #   - "5858:5858"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
volumes:
  postgres: